### ISSUE TITLE
lexical or preprocessor issues cocoa/cocoa.h file not found

### ISSUE THREAD

**Issue by RudyJessop** [profmaad/librabbitmq-objc#10]
I just added the librabbitmq-objc framework into my xcode project. I am currently getting an error `lexical or preprocessor issues cocoa/cocoa.h file not found` I would need someone to help me find the cocoa.h file.

Thanks

**Comment by profmaad** [comment]
Are you trying to use it in an iOS/iPhone project? If so, this is to be expected.
Cocoa is the Mac development framework, for iOS you will have to replace the includes with the corresponding iOS imports. Have a look at some of the forks, I'm sure a few of them are iOS-focused.

**Comment by RudyJessop** [comment]
AH YESS.! It makes total sense now. I was reading up on cocoa framework and wasn't paying attention to what I was readying. Thanks man. Stupid me.!
