### ISSUE TITLE
License is unusable

### ISSUE THREAD

**Issue by catshow** [profmaad/librabbitmq-objc#3]
Please change this license to a MPL instead of GPL.  That way people can use it in ios apps.

**Comment by fcvarela** [comment]
Or LGPL. catshow is right, this wrapper is unusable with this license.

**Comment by profmaad** [comment]
I changed the license to LGPLv3 with commit 9c7f067c1f293e617a31d06fe8738faf8e4d6f14.

**Comment by ghost** [comment]
Thank you for this, this makes all the difference! And also thank you for such an awesome wrapper!
