### ISSUE TITLE
about librabbitmq-objc using in IOS coding.

### ISSUE THREAD

**Issue by vbonluk** [profmaad/librabbitmq-objc#8]
I am a student learning your source . I come from China . My English is poor. so,don't laught at me.
When I want to buid a social app for my iPhone.
I found your source,and use it .
but ,I got some trouble.
You write that require :Cocoa and librabbitmq-c 
1:Cocoa whether meaning this source is using in Mac coding?
beacuse my Xcode is warning me . and then I change <"Cocoa/Cocoa.h"> to "<Foundation/Foundation.h>"
2:librabbitmq-c 
I don't know why your source have many wrong space in my project and I never change your source any more.
some space even lack parameter. 
Xcode wraning that:
file:

AMQPExchange.m

method:
- (id)initExchangeOfType:(NSString_)theType withName:(NSString_)theName onChannel:(AMQPChannel*)theChannel  isPassive:(BOOL)passive isDurable:(BOOL)durable getsAutoDeleted:(BOOL)autoDelete

wrong:
amqp_exchange_declare(theChannel.connection.internalConnection, theChannel.internalChannel, amqp_cstring_bytes([theName UTF8String]), amqp_cstring_bytes([theType UTF8String]), passive, durable, autoDelete, AMQP_EMPTY_TABLE);

say that :Toomany arguments to function call,expected 7,have 8.

2:

file 
AMQPMessage.h
wrong:
there no unit8 and unit64 ,but Xcode let me change to unit.

and your require Cocoa and librabbitmq - c
I don't know what librabbitmq - c harder I need to include ,because I found many source like that .But never adapt to your source.
Like 
https://github.com/ask/rabbitmq-c

please help me . I have been ........

**Comment by JuliaHudley** [comment]
i solved that problem following this post....try this it may help you.
http://stackoverflow.com/questions/22337432/how-should-i-use-the-library-as-librabbitmq-objc/24851421#24851421

**Comment by vbonluk** [comment]
I have been solved it with any ways.
include someone's static librabbitmq.a file.
and amq.h

I hope you can let it running independently‍ with out include file.
Because your project was show in http://www.rabbitmq.com/‍.
and only no one write it using OC,expect you.

There is my project for testing RabbitMQ.

Thanks for your reply.

------------------ 原始邮件 ------------------
发件人: "JuliaHudley";notifications@github.com;
发送时间: 2014年9月23日(星期二) 下午5:39
收件人: "profmaad/librabbitmq-objc"librabbitmq-objc@noreply.github.com; 
抄送: "Vboom🎈"5914018@qq.com; 
主题: Re: [librabbitmq-objc] about librabbitmq-objc using in IOS coding.(#8)

i solved that problem following this post....try this it may help you.
http://stackoverflow.com/questions/22337432/how-should-i-use-the-library-as-librabbitmq-objc/24851421#24851421

**Comment by JuliaHudley** [comment]
You are most welcome. @lu5914018
